# .github/workflows/main.yml

name: CI
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  test-ruby:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        os: [ubuntu]
        ruby-version: ["3.1", "3.2", "3.3"]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - name: Build and run tests
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
          bundle exec rspec spec
